/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e6e8eb',
        'on-tertiary-fixed-variant': '#852300',
        'secondary': '#006e2a',
        'on-secondary-fixed-variant': '#00531e',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'on-secondary-container': '#00732c',
        'outline-variant': '#c6c5d4',
        'primary': '#000666',
        'tertiary-fixed': '#ffdbd0',
        'on-primary-fixed': '#000767',
        'inverse-primary': '#bdc2ff',
        'error-container': '#ffdad6',
        'on-background': '#191c1e',
        'primary-fixed-dim': '#bdc2ff',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#390a00',
        'on-surface-variant': '#454652',
        'surface': '#f7f9fc',
        'surface-variant': '#e0e3e6',
        'on-error': '#ffffff',
        'surface-dim': '#d8dadd',
        'error': '#ba1a1a',
        'secondary-fixed': '#69ff87',
        'secondary-container': '#5cfd80',
        'on-surface': '#191c1e',
        'on-error-container': '#93000a',
        'tertiary-container': '#5d1600',
        'primary-fixed': '#e0e0ff',
        'surface-bright': '#f7f9fc',
        'on-primary-container': '#8690ee',
        'on-secondary': '#ffffff',
        'surface-tint': '#4c56af',
        'on-tertiary-fixed': '#3a0a00',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e0e3e6',
        'inverse-surface': '#2d3133',
        'secondary-fixed-dim': '#3ce36a',
        'outline': '#767683',
        'on-primary-fixed-variant': '#343d96',
        'primary-container': '#1a237e',
        'background': '#f7f9fc',
        'inverse-on-surface': '#eff1f4',
        'on-secondary-fixed': '#002108',
        'tertiary-fixed-dim': '#ffb59f',
        'on-tertiary-container': '#f96b3f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Be Vietnam Pro"', 'sans-serif'],
        label: ['"Be Vietnam Pro"', 'sans-serif'],
      },
      boxShadow: {
        glass: '0 8px 32px rgba(0, 6, 102, 0.08)',
        card: '0 2px 12px rgba(0, 6, 102, 0.06)',
      },
    },
  },
  plugins: [],
};
